# Generated by Django 5.2.15 on 2026-06-10 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('default_warranty_months', models.PositiveIntegerField(default=12, help_text='อายุประกัน default สำหรับชนิดนี้ (เดือน)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='รหัสย่อ plant (placeholder ก่อน — ใช้ของจริงทีหลัง)', max_length=8, unique=True)),
                ('name_th', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SnPrefix',
            fields=[
                ('prefix', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='PMRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (ก.พ.–มี.ค.)'), ('Q2', 'Q2 (พ.ค.–ก.ค.)'), ('Q3', 'Q3 (ก.ย.–พ.ย.)')], max_length=2)),
                ('field_start_date', models.DateField(help_text='วันเริ่มงานภาคสนาม')),
                ('field_end_date', models.DateField(help_text='วันจบงานภาคสนาม')),
                ('document_due_date', models.DateField(help_text='กำหนดส่งเอกสาร — ใช้เป็น warranty anchor')),
            ],
            options={
                'ordering': ['year', 'quarter'],
                'constraints': [models.UniqueConstraint(fields=('year', 'quarter'), name='unique_pmround_year_quarter')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('warranty_months_override', models.PositiveIntegerField(blank=True, help_text='ถ้าไม่ใส่ ใช้ default ของ asset_type', null=True)),
                ('is_retired', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.assettype')),
                ('replaced_predecessor', models.OneToOneField(blank=True, help_text='เครื่องเก่าที่ถูกเครื่องนี้แทน', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='inventory.device')),
                ('home_plant', models.ForeignKey(blank=True, help_text='plant เจ้าของ (null ได้ถ้า legacy ไม่ทราบ)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_devices', to='inventory.plant')),
                ('received_round', models.ForeignKey(blank=True, help_text='รอบที่รับเครื่อง (null = legacy ก่อนระบบ → ใช้ SnPrefix.year เป็น fallback)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_devices', to='inventory.pmround')),
                ('retired_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_devices', to='inventory.pmround')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='PlantRoundNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_notes', to='inventory.plant')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pm_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_notes', to='inventory.pmround')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'pm_round'), name='unique_plantroundnote')],
            },
        ),
        migrations.CreateModel(
            name='PMSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_use', 'ใช้งานปกติ'), ('new_delivery', 'รับเครื่องใหม่'), ('retired', 'เสื่อมสภาพ/คืน Enco'), ('borrowed_in', 'ยืมเข้ามาใช้'), ('loaned_out', 'ถูกยืมออกไป'), ('correction', 'แก้ไขข้อมูล')], default='in_use', max_length=16)),
                ('note', models.TextField(blank=True, help_text='ข้อความหมายเหตุดิบ')),
                ('checklist_results', models.JSONField(blank=True, help_text='ขยายสำหรับ Role inspector (future)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_snapshots', to='inventory.device')),
                ('plant', models.ForeignKey(help_text='plant ที่เครื่องอยู่ในรอบนี้ (อาจ ≠ home_plant กรณีถูกยืม)', on_delete=django.db.models.deletion.PROTECT, related_name='hosted_snapshots', to='inventory.plant')),
                ('pm_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='inventory.pmround')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pm_round__year', '-pm_round__quarter', 'plant__code', 'device__serial_number'],
                'indexes': [models.Index(fields=['pm_round', 'plant'], name='inventory_p_pm_roun_ab1583_idx'), models.Index(fields=['device', 'pm_round'], name='inventory_p_device__5e6280_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'pm_round'), name='unique_snapshot_per_device_round')],
            },
        ),
    ]
